### ISSUE TITLE
Pyramid written incorrectly unless resampleToZoom is called

### ISSUE THREAD

**Issue by RickMohr** [geotrellis/geotrellis#1566] opened 2016-06-29 15:10 UTC
In [this app](https://github.com/RickMohr/treecanopy-ingest/blob/harrisburg-merge/src/main/scala/treecanopy/Main.scala), a "statewide" PA tree canopy raster is merged with a "local" tree canopy raster from Harrisburg. Both datasets have 1 meter resolution, making a pyramid with max zoom 17. 

When I call `resampleToZoom` to zoom 18 [here](https://github.com/RickMohr/treecanopy-ingest/blob/harrisburg-merge/src/main/scala/treecanopy/Main.scala#L104), the pyramid is written correctly. For example, zoom level 11 contains tiles for x={586,587} But if `tiled` is returned without calling `resampleToZoom`, the pyramid is written incorrectly. For example, zoom level 11 contains tiles for x={1172,1173,1174}.

Note that both rasters are small (`raw/treecanopy-2006-2008-pennsylvania-temp` is a small subset of the full statewide raster) so this runs fairly quickly (2 minutes on a 5-node EMR cluster).

**Comment by RickMohr** [comment] 2016-06-30 14:26
I suspect this is related to another incorrect behavior I see when merging 6 local canopy rasters with the full statewide canopy raster. 5 of the 6 local rasters are merged correctly but one is not merged at all. The failing local raster has 1 foot resolution, so `resampleToZoom` is not called on it. Seems likely to be related.

**Comment by fosskers** [comment] 2016-09-30 18:37
Is this still a problem, @RickMohr ?

**Comment by RickMohr** [comment] 2016-09-30 18:55
We won't know unless somebody takes the time to try that app with a newer version of GT. I kept it on a branch and used small datasets specifically so it could be run by others. I'd be happy to support anyone who wants to give it a shot.

**Comment by echeipesh** [comment] 2016-10-28 16:00
Took on investigating this issue.

So far I've been able to take the data and use the code and perform the tiling. All the layers get tiled to zoom 18 from so the branch for `resampleToZoom` does not get called. The keys also appear on point.

It's a little hard to guess when this issue existed because project depend on `SNAPSHOT` version of GeoTrellis but it does not appear to be there.

I'm guessing this project does not need to update for the issue to be closed since the layer has already been produced?

I will attempt to render the layers to verify visually but I think this can be provisionally considered CNR.

**Comment by echeipesh** [comment] 2016-10-28 20:22
Ingest reproduced without usage of `resampleToZoom`
![image](https://cloud.githubusercontent.com/assets/1158084/19821109/a52a6746-9d2a-11e6-8b94-91d7d9b2f5b8.png)

Appears to be correct. Closing this issue.

**Closed by echeipesh** 2016-10-28 20:22 UTC
Labels: weight-2
